weights: yolov5s.pt
cfg: /Users/atmavidyavirananda/Documents/Univ/Tingkat 4/Semester 8/TA II/Code/YOLOv5/yolov5/models/yolov5s.yaml
data: /Users/atmavidyavirananda/Documents/Univ/Tingkat 4/Semester 8/TA II/Code/YOLOv5/yolov5/data/car_damage.yaml
hyp: /Users/atmavidyavirananda/Documents/Univ/Tingkat 4/Semester 8/TA II/Code/YOLOv5/yolov5/data/hyps/hyp.scratch-high.yaml
epochs: 20
batch_size: 16
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: runs/train
name: yolo_car_dmg
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/yolo_car_dmg2
